# -*- coding: utf-8 -*-

from __future__ import division

#CONSTANTES

ANCHO_VENTANA = 800
ALTO_VENTANA = 500

LINHA_BORRADO_Y = -100

TEMPO_ESPERA_MOUSE = 10

RADIO_BOLA = 2.5

TAMANHO_MAX_RECT_ANCHO = 15
TAMANHO_MAX_RECT_ALTO = 15

TAMANHO_MIN_RECT_ANCHO = 0.5
TAMANHO_MIN_RECT_ALTO = 0.5

#MEDIDA OPENGL

ANCHO_GL = 200
ALTO_GL = ANCHO_GL*ALTO_VENTANA/ANCHO_VENTANA

COLOR_FONDO = 0.1